// <auto-generated />
using System;
using Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entity.Migrations.Postgres
{
    [DbContext(typeof(ApplicationContextPostgres))]
    partial class ApplicationContextPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "Manages system modules, allowing users to define, modify, and assign modules available to them based on established roles and permissions.",
                            Icon = "fa-solid fa-window-maximize",
                            Name = "Modules",
                            Order = 1,
                            Path = "security/modules",
                            State = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "Manages the forms available in the system, allowing the creation, modification, and deletion of forms associated with different functionalities and modules.",
                            Icon = "fa-solid fa-window-restore",
                            Name = "Forms",
                            Order = 2,
                            Path = "security/forms",
                            State = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "Allows you to assign specific permissions to users and roles, controlling access to functions, forms, and modules according to the system's needs and security policies.",
                            Icon = "fa-solid fa-user-lock",
                            Name = "Permissions",
                            Order = 3,
                            Path = "security/permissions",
                            State = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "Defines and manages roles within the system, allowing you to assign specific permissions to each role and control access to different application features and resources.",
                            Icon = "fa-solid fa-users-gear",
                            Name = "Roles",
                            Order = 4,
                            Path = "security/roles",
                            State = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "It allows you to manage user information, including its creation, editing, and deletion. It facilitates the assignment of roles and permissions, ensuring controlled access to the system.",
                            Icon = "fa-solid fa-users",
                            Name = "Users",
                            Order = 5,
                            Path = "security/users",
                            State = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "It allows you to manage the information of people associated with the system, such as users, employees, or any other relevant entity. It facilitates the creation, editing, and deletion of records, allowing you to link people to specific roles, modules, and permissions as needed.",
                            Icon = "fa-solid fa-user",
                            Name = "Persons",
                            Order = 6,
                            Path = "security/persons",
                            State = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "This form allows the registration and management of customers within the system. It facilitates the creation, editing, and tracking of customer records, enabling the association of relevant operational data and interactions essential for service delivery and follow-up.",
                            Icon = "fa-solid fa-building-user",
                            Name = "Customers",
                            Order = 1,
                            Path = "operational/customers",
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.FormModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("ModuleId");

                    b.ToTable("FormModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 1,
                            ModuleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 2,
                            ModuleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 3,
                            ModuleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 4,
                            ModuleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 5,
                            ModuleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 6,
                            ModuleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 7,
                            ModuleId = 2,
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.ModelosParametros.Criteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("Entity.Models.ModelosParametros.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("Entity.Models.ModelosParametros.LineThematic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LineThematics");
                });

            modelBuilder.Entity("Entity.Models.ModelosParametros.PopulationGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PopulationGrade");
                });

            modelBuilder.Entity("Entity.Models.ModelosParametros.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Entity.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "The security module manages authentication, roles, permissions, and access to the system's forms and modules, ensuring the control and protection of information.",
                            Name = "Security",
                            State = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "The operational module manages the system's core functional forms, allowing users to execute day-to-day activities",
                            Name = "Operational",
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "0001",
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "Allows the user to query, update, and delete records within the system, granting full access to the management of associated data.",
                            Name = "Reading and writing",
                            State = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "0002",
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "Allows the user to only view records within the system, without permission to perform updates or deletions.",
                            Name = "Reading only",
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeDane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailInstitutional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeDane = "441001004839",
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            DocumentType = 1,
                            Email = "mariaalejan1080@gmail.com",
                            EmailInstitutional = "mariaa_marinh@soy.sena.com",
                            FirstLastName = "MARIN",
                            FirstName = "MARIA",
                            IdentificationNumber = "1000000000",
                            MiddleName = "ALEJANDRA",
                            Phone = 3243652328L,
                            SecondLastName = "HENRIQUEZ",
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "01",
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Description = "",
                            Name = "SUPERADMIN",
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.RoleFormPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleFormPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 1,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 2,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 3,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 4,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 5,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 6,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            FormId = 7,
                            PermissionId = 1,
                            RoleId = 1,
                            State = true
                        });
                });

            modelBuilder.Entity("Entity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "0001",
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            Password = "202CB962AC59075B964B07152D234B70",
                            PersonId = 1,
                            State = true,
                            Username = "mariaalejan1080@gmail.com"
                        });
                });

            modelBuilder.Entity("Entity.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 38, 26, 263, DateTimeKind.Utc).AddTicks(4612),
                            RoleId = 1,
                            State = true,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Models.FormModule", b =>
                {
                    b.HasOne("Entity.Models.Form", "Form")
                        .WithMany("FormModules")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Module", "Module")
                        .WithMany("FormModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Entity.Models.RoleFormPermission", b =>
                {
                    b.HasOne("Entity.Models.Form", "Form")
                        .WithMany("RoleFormPermissions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Permission", "Permission")
                        .WithMany("RoleFormPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Role", "Role")
                        .WithMany("RoleFormPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Models.User", b =>
                {
                    b.HasOne("Entity.Models.Person", "Person")
                        .WithMany("User")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entity.Models.UserRole", b =>
                {
                    b.HasOne("Entity.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Models.Form", b =>
                {
                    b.Navigation("FormModules");

                    b.Navigation("RoleFormPermissions");
                });

            modelBuilder.Entity("Entity.Models.Module", b =>
                {
                    b.Navigation("FormModules");
                });

            modelBuilder.Entity("Entity.Models.Permission", b =>
                {
                    b.Navigation("RoleFormPermissions");
                });

            modelBuilder.Entity("Entity.Models.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Models.Role", b =>
                {
                    b.Navigation("RoleFormPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Entity.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
